# -*-mode:yaml-*- vim:ft=yaml
x-TZ:
  &TZ
  TZ: 'Asia/Tokyo'

services:
  app:
    build:
      context: ${APP_ROOT}
      dockerfile: Dockerfile
    init: true
    user: ${APP_USER}
    environment:
      LANG: ${APP_LANG}
      <<: *TZ
    volumes:
      - .:/app
